## Pandas 

pandas is a powerful, open-source Python library used primarily for data manipulation, data analysis, and data cleaning. Think of it as a way to use spreadsheets (like Excel) or databases (like SQL) directly inside your Python code, but with significantly more speed and flexibility.

In [3]:
!pip install pandas


In [4]:
import pandas as pd

   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 7.0 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/9.9 MB 8.2 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.9 MB 8.1 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/9.9 MB 7.3 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 6.7 MB/s  0:00:01
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----------- ---------------------------- 3.7/12.6 MB 10.9 MB/s eta 0:00:01
   ---------------- ----------------------- 5.2/12.6 MB 9.4 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 8.6 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.6 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 8.3 MB/s eta 0:00:01
   -----------------

In [5]:
import pandas as pd

In [6]:
import numpy as np

## NumPy (short for Numerical Python) 
is the foundational open-source library for scientific computing and mathematical operations in Python

In [8]:
data = np.array([[1,4] ,[2,5],[3,6]])
data

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
df =pd.DataFrame(data,index=['row1','row2','row3'],
                 columns=['col1','col2'])

In [10]:
df

,col1,col2
row1,1,4
row2,2,5
row3,3,6


In [11]:
data1 = np.array([[2,3,7,9],[4,5,3,7],[6,6,4,2],[7,7,4,3],[8,8,6,4]])
data1

array([[2, 3, 7, 9],
       [4, 5, 3, 7],
       [6, 6, 4, 2],
       [7, 7, 4, 3],
       [8, 8, 6, 4]])

In [14]:
df1 = pd.DataFrame(data1,index=['row1','row2','row3','row4','row5'],
                   columns=['col1','col2','col3','col4'])

In [15]:
df1

,col1,col2,col3,col4
row1,2,3,7,9
row2,4,5,3,7
row3,6,6,4,2
row4,7,7,4,3
row5,8,8,6,4


In [16]:
data2 = np.array([[2.333,3.555,7,9],[4,5,3,7],[6,6,4,2],[7,7,4,3],[8,8,6,4]])
data2

array([[2.333, 3.555, 7.   , 9.   ],
       [4.   , 5.   , 3.   , 7.   ],
       [6.   , 6.   , 4.   , 2.   ],
       [7.   , 7.   , 4.   , 3.   ],
       [8.   , 8.   , 6.   , 4.   ]])

In [17]:
df2 = pd.DataFrame(data2,index=['row1','row2','row3','row4','row5'],
                   columns=['col1','col2','col3','col4'])

In [18]:
df2

,col1,col2,col3,col4
row1,2.333,3.555,7.0,9.0
row2,4.000,5.000,3.0,7.0
row3,6.000,6.000,4.0,2.0
row4,7.000,7.000,4.0,3.0
row5,8.000,8.000,6.0,4.0


In [19]:
states = ['Maharashtra','Telangana','Delhi','Rajasthan']
population = [129300000,83879000,38665000,23000000]

In [20]:
dict_states = {'States':states,'Population':population}
dict_states

{'States': ['Maharashtra', 'Telangana', 'Delhi', 'Rajasthan'],
 'Population': [129300000, 83879000, 38665000, 23000000]}

In [21]:
India = pd.DataFrame(dict_states)

In [22]:
India

,States,Population
0,Maharashtra,129300000
1,Telangana,83879000
2,Delhi,38665000
3,Rajasthan,23000000


In [23]:
import pandas as pd

In [25]:
df =pd.read_csv(r"C:\Python\StudentsPerformance.csv")

In [26]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77


In [27]:
import pandas as pd

In [29]:
df = pd.read_csv(r"C:\Python\StudentsPerformance.csv")

In [30]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77


In [31]:
df = pd.read_csv("https://raw.githubusercontent.com/ItsFaizan-official/Python-for-Data-Science/refs/heads/main/python-for-data-science-main/02.Intro%20to%20Pandas/StudentsPerformance.csv")

In [32]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77


In [33]:
import pandas as pd

In [34]:
df2 = pd.read_csv("https://raw.githubusercontent.com/ItsFaizan-official/Python-for-Data-Science/refs/heads/main/python-for-data-science-main/02.Intro%20to%20Pandas/StudentsPerformance.csv")

In [35]:
df2

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
